set-option -g status-right '#H %H:%M %Y-%m-%d'
set-option -g set-titles on
set-option -g set-titles-string '#S@#H'
run-shell "tmux set-option -g status-bg colour$((0x$(hostname | md5sum | cut -c1-2)))"

unbind C-b
set -g prefix C-a
bind C-a send-prefix

